
package swing;
import javax.swing.*;
public class MenuDemo {
    MenuDemo(){
        JFrame f=new JFrame("Menu Bar");
        f.setSize(500, 500);// size of window/container....
        f.setVisible(true);// defult is false so changing.....
        f.setLayout(null);// defining layout......
        f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);// closes program after exiting.......
        
        JMenuBar mb= new JMenuBar();// menu bar....
        JMenu file= new JMenu("File");// menu....
        JMenu edit= new JMenu("Edit");
        JMenuItem i1=new JMenuItem("Open");// menu items......
        JMenuItem i2=new JMenuItem("Save");
        file.add(i1); file.add(i2);// adding menuitems to menu....
        mb.add(file); mb.add(edit);// adding menu to menu bar........
        f.setJMenuBar(mb);  // adding menubar to frame......... 
    }
    public static void main(String args[]){
            new MenuDemo();// call.....
        }
}
